# Generated by Django 4.2.10 on 2024-02-16 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_blogpost_publish_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost", name="publish_date", field=models.DateTimeField(),
        ),
    ]
