# Generated by Django 4.2.10 on 2024-02-16 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(old_name="Skill", new_name="service",),
    ]
