# Generated by Django 4.2.10 on 2024-02-16 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0002_rename_skill_service"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="icon_name",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
