# Generated by Django 3.2.7 on 2024-02-16 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('i_am', models.CharField(max_length=20)),
                ('based_in', models.CharField(max_length=100)),
                ('description_one', models.TextField()),
                ('description_two', models.TextField()),
                ('signature_image', models.ImageField(upload_to='about/signatures/')),
                ('projects_completed', models.PositiveIntegerField(default=0)),
                ('cups_of_coffee', models.PositiveIntegerField(default=0)),
                ('satisfied_clients', models.PositiveIntegerField(default=0)),
                ('total_certificate', models.PositiveIntegerField(default=0)),
                ('years_of_experience', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'About',
                'verbose_name_plural': 'About',
            },
        ),
    ]
