# Generated by Django 4.2.10 on 2024-02-16 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("author_name", models.CharField(max_length=100)),
                ("author_position", models.CharField(max_length=100)),
                ("author_image", models.ImageField(upload_to="testimonials/")),
                ("feedback", models.TextField()),
            ],
        ),
    ]
