# Generated by Django 4.2.10 on 2024-02-16 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0002_testimonial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testimonial",
            name="author_image",
            field=models.ImageField(blank=True, null=True, upload_to="testimonials/"),
        ),
    ]
