# Generated by Django 4.2.10 on 2024-02-16 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Portfolio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("thumbnail", models.ImageField(upload_to="portfolio/")),
                ("link", models.URLField()),
            ],
            options={"verbose_name": "Portfolio", "verbose_name_plural": "Portfolio",},
        ),
    ]
