# Generated by Django 4.2.10 on 2024-11-12 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="portfolio",
            name="slug",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
