# Generated by Django 4.2.10 on 2024-02-16 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Experience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.CharField(max_length=100)),
                ("company_name", models.CharField(max_length=200)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "working_type",
                    models.CharField(
                        choices=[
                            ("Full-time", "Full-time"),
                            ("Part-time", "Part-time"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "mode_of_work",
                    models.CharField(
                        choices=[
                            ("Freelancer", "Freelancer"),
                            ("Contract", "Contract"),
                            ("Personal Project", "Personal Project"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "work_location",
                    models.CharField(
                        choices=[
                            ("In office", "In office"),
                            ("Remotely", "Remotely"),
                            ("Hybrid", "Hybrid"),
                        ],
                        max_length=50,
                    ),
                ),
            ],
        ),
    ]
