# Generated by Django 4.2.10 on 2024-02-16 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume", "0003_remove_experience_working_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="experience",
            name="end_date",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="End Date"
            ),
        ),
        migrations.AlterField(
            model_name="experience",
            name="start_date",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Start Date"
            ),
        ),
    ]
