# Generated by Django 4.2.10 on 2024-02-16 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume", "0004_alter_experience_end_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="experience",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
