# Generated by Django 4.2.10 on 2024-02-16 13:54

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ("resume", "0005_experience_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="experience",
            name="experience_letter",
            field=models.FileField(
                blank=True, null=True, upload_to="experience_letters/"
            ),
        ),
        migrations.AddField(
            model_name="experience",
            name="link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="education",
            name="description",
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="experience",
            name="description",
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
        ),
    ]
