# Generated by Django 4.2.10 on 2024-02-16 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("resume", "0008_mycv"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mycv",
            options={"verbose_name": "My CV", "verbose_name_plural": "My CV"},
        ),
    ]
